SQLALCHEMY_DATABASE_URI = "postgresql://postgres:admin2255@localhost:5432/dams"
SECRET_KEY = "SpOn1ZyV4KE2FTlAUrWRZ_h7o5s"
FLASK_DEBUG = true
TESTING = true


CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

[CELERY]
celery_store_errors_even_if_ignored = true
task_create_missing_queues = true
task_store_errors_even_if_ignored = true 
task_ignore_result = false
broker_connection_retry_on_startup = true
celery_task_serializer = "pickle"
celery_result_serializer = "pickle"
celery_event_serializer = "json"
celery_accept_content = ["pickle", "application/json", "application/x-python-serialize"]
celery_result_accept_content = ["pickle", "application/json", "application/x-python-serialize"]
