SQLALCHEMY_DATABASE_URI = "postgresql://postgres:admin2255@localhost:5433/ovs"
SECRET_KEY = "SpOn1ZyV4KE2FTlAUrWRZ_h7o5s"
FLASK_DEBUG = true
TESTING = true

PYTHON_JULIAPKG_EXE = "C:/Alibata/Development/Language/Julia-1.9.2/bin/julia"
PYTHON_JULIAPKG_OFFLINE = "yes"
PYTHON_JULIAPKG_PROJECT = "C:/Alibata/Training/Source/flask/mastering/ch06-web-final/Ch06JuliaPkg/"
JULIA_CONDAPKG_BACKEND = "NULL"
JULIA_PYTHONCALL_EXE = "C:/Alibata/Training/Source/flask/mastering/ch06-web-env/Scripts/python"

UPLOAD_FILE_TYPES = [".csv", ".xls", ".doc", ".xlsx" ]
UPLOAD_FILE_PATH = "./files/xlsx/"
MAX_CONTENT_LENGTH = 209715200

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

[CELERY]
celery_store_errors_even_if_ignored = true
task_create_missing_queues = true
task_store_errors_even_if_ignored = true 
task_ignore_result = false
broker_connection_retry_on_startup = true
task_serializer = "pickle"
result_serializer = "pickle"
event_serializer = "json"
accept_content = ["pickle", "application/json", "application/x-python-serialize"]
result_accept_content = ["pickle", "application/json", "application/x-python-serialize"]
